Asp.Net Core/Assignments/24 - Assignment/StocksSolution/StocksSolution/Models/Stocks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Entities
{
    public class Stocks
    {
        public string? StockSymbol { get; set; }
        public string? StockName { get; set; }
    }
}

Asp.Net Core/Assignments/24 - Assignment/StocksSolution/StocksSolution/Controllers/StocksController.cs
using Entities;
using Exceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using ServiceContracts.FinnhubService;
using StockMarketSolution.Models;

namespace StockMarketSolution.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly TradingOptions _options;
        private readonly IFinnhubStocksService _finnhubStocksServices;
        private readonly ILogger<StocksController> _logger;
        public StocksController(IOptions<TradingOptions> options, IFinnhubStocksService finnhubStocksServices, ILogger<StocksController> logger)
        {
            _options = options.Value;
            _finnhubStocksServices = finnhubStocksServices;
            _logger = logger;
        }

        [Route("[action]/{stock?}")]
        [Route("~/[action]/{stock?}")]
        [Route("/")]
        [HttpGet]
        public async Task<IActionResult> Explore(string? stock, bool showAll = false)
        {
            _logger.LogInformation("In StocksController.Explore() action method");
            _logger.LogDebug($"stock: {stock}, showAll: {showAll}");

            if(_options.Top25PopularStocks == null)
                throw new InvalidOperationException("Cannot find popular stocks in configuration");
            string[] top25PopularStocks = _options.Top25PopularStocks.Split(',');
            
            List<Dictionary<string, string>>? stocksDictionary = await _finnhubStocksServices.GetStocks();
            if(stocksDictionary == null)
                throw new InvalidOperationException("No response from finnhub server");
            if(!showAll)
                stocksDictionary = stocksDictionary
                    .Where(temp => top25PopularStocks.Contains(Convert.ToString(temp["symbol"])))
                    .ToList();

            List<Stocks> stocks = new List<Stocks>();
            stocks = stocksDictionary
                .Select(temp => new Stocks()
                {
                    StockSymbol = temp["symbol"],
                    StockName = temp["description"]
                })
                .ToList();
            ViewBag.Stock = stock;
            return View(stocks);
        }
    }
}

Asp.Net Core/Assignments/24 - Assignment/StocksSolution/StocksSolution/ViewComponents/SelectedStockViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Repositories;
using ServiceContracts;
using ServiceContracts.FinnhubService;
using ServiceContracts.StockService;
using StockMarketSolution.Models;

namespace StockMarketSolution.ViewComponents
{
    public class SelectedStockViewComponent : ViewComponent
    {
        private readonly TradingOptions _tradingOptions;
        private readonly IFinnhubPriceQuoteService _finnhubPriceQuoteService;
        private readonly IFinnhubCompanyProfileService _finnhubCompanyProfileService;
        private readonly IConfiguration _configuration;
        public SelectedStockViewComponent(
            IOptions<TradingOptions> tradingOptions,
            IFinnhubPriceQuoteService finnhubPriceQuoteService,
            IFinnhubCompanyProfileService finnhubCompanyProfileService,
            IConfiguration configuration)
        {
            _tradingOptions = tradingOptions.Value;
            _finnhubPriceQuoteService = finnhubPriceQuoteService;
            _finnhubCompanyProfileService = finnhubCompanyProfileService;
            _configuration = configuration;
        }
        public async Task<IViewComponentResult> InvokeAsync(string stockSymbol)
        {
            if (stockSymbol != null)
            {
                Dictionary<string, object>? companyProfileDict = await _finnhubCompanyProfileService.GetCompanyProfile(stockSymbol);
                Dictionary<string, object>? stockPriceDict = await _finnhubPriceQuoteService.GetStockPriceQuote(stockSymbol);
                if (companyProfileDict != null && stockPriceDict != null)
                {
                    companyProfileDict.Add("price", stockPriceDict["c"]);
                }

                // Check if the stock symbol is valid
                if (companyProfileDict != null && companyProfileDict.ContainsKey("logo"))
                {
                    // Return the view with the stock symbol
                    return View("SelectedStock", companyProfileDict);
                }
            }
            // Handle the case where no data is found
            return Content("No data found for the given stock symbol.");
        }
    }
}

Asp.Net Core/Assignments/24 - Assignment/StocksSolution/StocksSolution/Views/Stocks/Explore.cshtml
@model IEnumerable<Stocks>
@{
	ViewBag.Title = "Explore";
	ViewBag.CurrentUrl = "~/Explore";
	ViewBag.PrintedUrl = "Explore";
}


<div class="flex stocks-list">
	<div class="flex-1" id="stocks-list">
		<div class="box">
			<div class="flex">
				<div class="flex-1">
					<h4 class="text-grey mb">Stocks</h4>
				</div>
				<div class="flex-1 text-right">
					<a href="~/stocks/explore?showAll=true" class="mr">Show all stocks</a>
				</div>
			</div>


			<ul class="list">
				@foreach (Stocks stock in Model)
				{
					<li>
						@if (Context.Request.Query.ContainsKey("showAll"))
						{
							<a href="~/stocks/explore/@stock.StockSymbol?showAll=@Context.Request.Query["showAll"]">
								<h5>@stock.StockName</h5>
								<p>@stock.StockSymbol</p>
							</a>
						}
						else
						{
							<a href="~/stocks/explore/@stock.StockSymbol">
								<h5>@stock.StockName</h5>
								<p>@stock.StockSymbol</p>
							</a>
						}
					</li>
				}
			</ul>
		</div>
	</div>

	@if (Model.Count() == 0)
	{
		<div class="mt text-blue">No stocks</div>
	}

	<div class="flex-1" id="stock-details">
		@if (ViewBag.Stock != null)
		{
			<vc:selected-stock stock-symbol=@ViewBag.Stock></vc:selected-stock>
		}
	</div>
</div>